
package com.test_soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PersonsPortService", targetNamespace = "http://www.test-soap.com/", wsdlLocation = "http://localhost:8080/ws/persons.wsdl")
public class PersonsPortService
    extends Service
{

    private final static URL PERSONSPORTSERVICE_WSDL_LOCATION;
    private final static WebServiceException PERSONSPORTSERVICE_EXCEPTION;
    private final static QName PERSONSPORTSERVICE_QNAME = new QName("http://www.test-soap.com/", "PersonsPortService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/ws/persons.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PERSONSPORTSERVICE_WSDL_LOCATION = url;
        PERSONSPORTSERVICE_EXCEPTION = e;
    }

    public PersonsPortService() {
        super(__getWsdlLocation(), PERSONSPORTSERVICE_QNAME);
    }

    public PersonsPortService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PERSONSPORTSERVICE_QNAME, features);
    }

    public PersonsPortService(URL wsdlLocation) {
        super(wsdlLocation, PERSONSPORTSERVICE_QNAME);
    }

    public PersonsPortService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PERSONSPORTSERVICE_QNAME, features);
    }

    public PersonsPortService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PersonsPortService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PersonsPort
     */
    @WebEndpoint(name = "PersonsPortSoap11")
    public PersonsPort getPersonsPortSoap11() {
        return super.getPort(new QName("http://www.test-soap.com/", "PersonsPortSoap11"), PersonsPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PersonsPort
     */
    @WebEndpoint(name = "PersonsPortSoap11")
    public PersonsPort getPersonsPortSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.test-soap.com/", "PersonsPortSoap11"), PersonsPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PERSONSPORTSERVICE_EXCEPTION!= null) {
            throw PERSONSPORTSERVICE_EXCEPTION;
        }
        return PERSONSPORTSERVICE_WSDL_LOCATION;
    }

}
