
package com.test_soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PersonsPort", targetNamespace = "http://www.test-soap.com/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PersonsPort {


    /**
     * 
     * @param getConvertedXmlRequest
     * @return
     *     returns com.test_soap.GetConvertedXmlResponse
     */
    @WebMethod
    @WebResult(name = "getConvertedXmlResponse", targetNamespace = "http://www.test-soap.com/", partName = "getConvertedXmlResponse")
    public GetConvertedXmlResponse getConvertedXml(
        @WebParam(name = "getConvertedXmlRequest", targetNamespace = "http://www.test-soap.com/", partName = "getConvertedXmlRequest")
        GetConvertedXmlRequest getConvertedXmlRequest);

}
